#!/usr/bin/env ansible-playbook
---

- name: Provision Hashicorp Vault
  hosts: vault_instances
  become: true
  become_user: root
  gather_facts: true

  roles:
    - role: hashicorp_vault
      tags: 'vault'

    - role: vault_admin
      tags: 'vault_admin'
