---

- name: Enable access in firewalld
  firewalld:
    port: '{{ item }}/tcp'
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - 8200
  tags:
    - firewalld

- name: Set transport
  set_fact:
    vault_transport: 'http'
  when: vault_tls_disable is defined and vault_tls_disable == 1

- name: Insert http(s) export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_ADDR={{ vault_transport }}://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
  tags:
    - init
    - config

- name: Insert CA cert export in dotfile
  lineinfile:
    path: '/etc/profile.d/vault.sh'
    line: "export VAULT_CACERT={{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    create: true
  when:
    - ansible_os_family != 'Windows'
    - not vault_tls_disable|bool
  tags:
    - init
    - config

...
